# Generated by Django 4.2.4 on 2023-08-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='id пользователя')),
                ('login', models.CharField(max_length=30, null=True, verbose_name='telegram-логин пользователя')),
            ],
            options={
                'verbose_name': 'Пользователи',
            },
        ),
    ]
