# Generated by Django 4.2.4 on 2023-08-11 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время регистрации')),
                ('telegram_id', models.BigIntegerField(null=True, unique=True, verbose_name='id пользователя')),
                ('telegram_login', models.CharField(max_length=30, null=True, verbose_name='логин пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, null=True, verbose_name='На регистрации')),
                ('bot_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.botuser', verbose_name='id пользователя')),
            ],
            options={
                'verbose_name': 'Состояние пользователя',
                'verbose_name_plural': 'Состояние пользователей',
            },
        ),
    ]
