# Generated by Django 4.2.4 on 2023-08-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True, verbose_name='Цена товара')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='Наименование товара')),
            ],
        ),
    ]
