# Generated by Django 4.2.4 on 2023-08-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_botuser_delete_userslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='login',
        ),
        migrations.AddField(
            model_name='botuser',
            name='telegram_id',
            field=models.BigIntegerField(default=0, unique=True, verbose_name='id пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botuser',
            name='telegram_login',
            field=models.CharField(max_length=30, null=True, verbose_name='логин пользователя'),
        ),
    ]
