# Generated by Django 4.2.4 on 2023-08-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_botuser_external_id_remove_botuser_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='На регистрации')),
            ],
            options={
                'verbose_name': 'Состояние пользователя',
                'verbose_name_plural': 'Состояние пользователей',
            },
        ),
        migrations.AlterField(
            model_name='botuser',
            name='telegram_id',
            field=models.BigIntegerField(null=True, unique=True, verbose_name='id пользователя'),
        ),
    ]
