# Generated by Django 4.2.4 on 2023-08-12 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_goods_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
