# Generated by Django 4.2.4 on 2023-08-11 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_state_alter_botuser_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 11, 5, 29, 3, 802326, tzinfo=datetime.timezone.utc), verbose_name='Время регистрации'),
        ),
    ]
