# Generated by Django 4.2.4 on 2023-08-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_goods_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='Наименование товара')),
                ('price', models.IntegerField(null=True, verbose_name='Стоимость услуги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AddField(
            model_name='state',
            name='options',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, null=True, verbose_name='На выборе товаров/услуг'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
    ]
