# Generated by Django 4.2.4 on 2023-08-11 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_botuser_register_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='register_time',
        ),
    ]
