# Generated by Django 4.2.4 on 2023-08-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_services_state_options_alter_goods_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Наименование услуги'),
        ),
    ]
