# Generated by Django 4.2.4 on 2023-08-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_services_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='options',
        ),
        migrations.AddField(
            model_name='state',
            name='goods',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, null=True, verbose_name='Выбор товаров'),
        ),
        migrations.AddField(
            model_name='state',
            name='services',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, null=True, verbose_name='Выбор услуг'),
        ),
        migrations.AlterField(
            model_name='state',
            name='registration',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=True, null=True, verbose_name='На регистрации'),
        ),
    ]
